### ISSUE TITLE
Met something wrong in the tutorial

### ISSUE THREAD

**Issue by shuhaom** [torchmd/torchmd-cg#30] opened 2023-04-19 04:42 UTC
Hi,

Thanks for developing and sharing the code! I'm trying to follow the notebook in the tutorial but get the following error while running the 10th code cell. 

```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 12
      9 device = 'cpu' 
     10 forceterms=["Bonds", "Angles", "RepulsionCG"]
---> 12 make_deltaforces(coords_npz, forces_npz, delta_forces_npz, forcefield, psf, exclusions, device, forceterms)

File ~/torchMD/torchmd-cg/torchmd_cg/utils/make_deltaforces.py:80, in make_deltaforces(coords_npz, forces_npz, delta_forces_npz, forcefield, psf, exclusions, device, forceterms)
     78 prior_forces = []
     79 for co in tqdm(coords):
---> 80     Epot = forces.compute(co.reshape([1, natoms, 3]), system.box, system.forces)
     81     fr = (
     82         system.forces.detach().cpu().numpy().astype(np.float32).reshape([natoms, 3])
     83     )
     84     prior_forces.append(fr)

File ~/torchMD/torchmd/torchmd/forces.py:293, in Forces.compute(self, pos, box, forces, returnDetails, explicit_forces)
    291     pot[i][v] += E.sum()
    292 elif v == "repulsioncg":
--> 293     E, force_coeff = evaluate_repulsion_CG(
    294         nb_dist,
    295         ava_idx,
    296         self.par.mapped_atom_types,
    297         self.par.B,
    298         explicit_forces,
    299     )
    300     pot[i][v] += E.sum()
    301 else:

File ~/torchMD/torchmd/torchmd/forces.py:432, in evaluate_repulsion_CG(dist, pair_indeces, atom_types, B, scale, explicit_forces)
    428 atomtype_indices = atom_types[pair_indeces]
    430 print(atomtype_indices,atomtype_indices[:, 0], atomtype_indices[:, 1],B)
--> 432 coef = B[atomtype_indices[:, 0], atomtype_indices[:, 1]]
    434 rinv1 = 1 / dist
    435 rinv6 = rinv1**6

TypeError: 'NoneType' object is not subscriptable`
```

I tried to print the values _atomtype_indices_ and _B_ and I found that _B_ is **_none_**

Can you tell me the possible reason?

**Comment by shuhaom** [comment] 2023-04-20 10:20
I find that in the current _**torchmd**_ version, **"RepulsionCG"** is not defined for retrieval in the _**Parameters.py**_.  

And the same bug will occur when running the simulate.yaml

**Comment by andrewrgarcia** [comment] 2023-05-13 22:13
I had the same issue. 

In section 1.3. of your code, replace forceterms list as below:

```ruby

from torchmd_cg.utils.make_deltaforces import make_deltaforces

coords_npz = 'data/chignolin_ca_coords.npy'
forces_npz = 'data/chignolin_ca_forces.npy'
delta_forces_npz = 'data/chignolin_ca_deltaforces.npy'      # this is the name of the file to be saved; delta_forces_npz is created by make_deltaforces
forcefield = 'data/chignolin_priors.yaml' 
psf = 'data/chignolin_ca_top.psf'
exclusions = ('bonds')
device = 'cpu' 
# forceterms = ['Bonds','RepulsionCG'],
forceterms = ['bonds','repulsioncg','lj']
make_deltaforces(coords_npz, forces_npz, delta_forces_npz, forcefield, psf, exclusions, device, forceterms)

```

This worked for me. Don't forget to close the issue. 

Regards, 
Andrew

**Closed as completed** 2023-05-14 03:46 UTC

**Comment by stefdoerr** [comment] 2023-05-15 09:14
Hi, @shuhaom what version of torchmd are you using?
```
conda list torchmd
```
Because this should not be an issue in the latest one as far as I know.

**Comment by andrewrgarcia** [comment] 2023-05-20 20:38
> Hi, @shuhaom what version of torchmd are you using?
> 
> ```
> conda list torchmd
> ```
> 
> Because this should not be an issue in the latest one as far as I know.

Hi @stefdoerr ,

This is the version of torchmd I am using 
```
# packages in environment at /home/andrew/anaconda3/envs/torchmd:
#
# Name                    Version                   Build  Channel
torchmd                   0.0.4                    pypi_0    pypi

```
I think it is the latest version and I also had the same issue that @shuhaom had. With the work-around I provided of replacing `forceterms `with   ['bonds','repulsioncg','lj'],  the problem is resolved; I found from the library code that some calculations needed for the tutorial depended on LJ. 

Regards, 
Andrew

**Comment by ARKAtheVLOGGER** [comment] 2024-03-27 23:02
do you know how to create forces_npz = 'data/chignolin_ca_forces.npy' &  coords_npz = 'data/chignolin_ca_coords.npy'??
Coordinate file can be made from .dcd file. but what about force file?
